kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: devopsbatches.devops.com
spec:
  group: devops.com
  names:
    kind: DevOpsBatch
    listKind: DevOpsBatchList
    plural: devopsbatches
    singular: devopsbatch
    shortNames:
      - dob
      - devops
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
                description: "Name of the batch"
              duration:
                type: integer
                description: "Duration of the batch"
              mode:
                type: string
                description: "Mode of the batch"
              platform:
                type: string
                description: "Platform of the batch"
