apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  namespace: default
  labels:
    app: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath: /mnt/data
