apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: apache-manager
  namespace: apache
  spec:
    rules:
      - apiGroups: ["apps", " ", "rbac.authorization.k8s.io"]
        resources: ["deployments", "pods", "services"]
        verbs:
          [
            "get",
            "list",
            "watch",
            "create",
            "update",
            "patch",
            "delete",
            "apply",
          ]
